acquisitions/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web import views as web_views
from nda import views as nda_views
from team import urls as team_urls
from projects import urls as projects_urls
from projects import views as project_views
from news import urls as news_urls
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_docs.views import DRFDocsView


api_patterns = projects_urls.api_patterns + team_urls.api_patterns


urlpatterns = [
    url(r'^$', web_views.index),
    url(r'^guides$', web_views.guides),
    url(r'^api/$', DRFDocsView.as_view(), name='api_docs'),
    url(r'^api/', include(api_patterns, namespace='api')),
    url(r'^financials$', project_views.financials, name='financials'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^team/', include(team_urls.urlpatterns, namespace='team')),
    url(
        r'^projects/',
        include(projects_urls.project_patterns, namespace='projects')
    ),
    url(
        r'^buys/',
        include(projects_urls.buy_patterns, namespace='buys')
    ),
    url(
        r'^iaas/',
        include(projects_urls.iaa_patterns, namespace='iaas')
    ),
    url(
        r'^clients/',
        include(projects_urls.client_patterns, namespace='clients')
    ),
    url(
        r'^news/',
        include(news_urls.urlpatterns, namespace='news')
    ),
    url(r'^profile/$', web_views.profile),
    url(r'^profile/refresh_token/$', web_views.refresh_token),
    url(r'^profile/sign_nda/$', nda_views.sign_nda),
    # url(r'^auth/', include('uaa_client.urls', namespace='uaa_client')),
    url(r'^auth/', include('uaa_client.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^', include('uaa_client.fake_uaa_provider.urls',
                          namespace='fake_uaa_provider'))
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import include, url
from news import views
from news.feeds import LatestPosts

urlpatterns = [
    url(r'^$', views.posts, name='posts'),
    url(r'^rss/$', LatestPosts(), name='rss'),
    url(r'^(?P<slug>[a-z\-]+)$', views.post, name='post'),
]

news/models.py
from datetime import datetime
from dateutil.tz import tzlocal
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    title = models.CharField(
        max_length=100,
        blank=False,
        null=False,
    )
    slug = models.SlugField(
        max_length=50,
        blank=True,
        null=True,
    )
    authors = models.ManyToManyField(
        User,
        blank=False,
    )
    content = models.TextField(
        blank=False,
        null=False,
    )
    publication_date = models.DateTimeField(
        blank=True,
        null=True,
    )
    draft = models.BooleanField(
        default=True,
    )

    def __str__(self):
        return "{0} | {1}".format(self.title, self.publication_date)

    def get_absolute_url(self):
        return reverse('news:post', args=[self.slug])

    def clean(self):
        if self.draft and self.publication_date is not None:
            raise ValidationError({
                'publication_date': 'Drafts may not have a publication date'
            })
        if not self.draft and self.publication_date is None:
            raise ValidationError({
                'publication_date': 'Please set a publication date'
            })

    class Meta:
        pass

news/views.py
from datetime import datetime
from dateutil.tz import tzlocal
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from news.models import Post


# Create your views here.
def posts(request):
    post_list = Post.objects.filter(
        draft=False,
        publication_date__lte=datetime.now(tzlocal())
    ).order_by('publication_date')
    # Pagination: https://docs.djangoproject.com/en/1.10/topics/pagination/
    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    return render(request, "news/posts.html", {"posts": posts})


def post(request, slug):
    post = get_object_or_404(
        Post,
        slug=slug,
        draft=False,
        publication_date__lte=datetime.now(tzlocal()),
    )
    return render(request, "news/post.html", {'post': post})

news/templates/news/post.html
{% extends "web/base.html" %}

{% block content %}
  <section class="usa-grid">
    <div class="usa-width-one-full">
      <h1>{{ post.title }}</h1>
      <div class="post-content">
        {{ post.content }}
      </div>
    </div>
  </section>
{% endblock %}

news/templates/news/posts.html
{% extends "web/base.html" %}
{% load static from staticfiles %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <h1>All updates</h1>
    {% for post in posts %}
    <h2>{{ post.title }}</h2>
    <p class="post-publication-info">
      <small>Posted on {{ post.publication_date }}<br>by {% for author in post.authors.all %}
        {{ author.get_full_name }}{% if not forloop.last %}, {% endif %}
      {% endfor %}</small>
    </p>
    <div class="post-content">
      {{ post.content }}
      <p><small><a href="{% url 'news:post' post.slug %}">Permalink</a></small></p>
    </div>
    {% empty %}
    <p>No updates yet, but stay tuned!</p>
    {% endfor %}
    <hr />
    <div class="pagination">
      <span class="step-links">
        {% if posts.has_previous %}
        <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>

        {% if posts.has_next %}
        <a href="?page={{ posts.next_page_number }}">next</a>
        {% endif %}
      </span>
    </div>
    <div class="rss-feed">
      <p><a href="{% url 'news:rss' %}">RSS Feed <img width=20 src="{% static "img/social-icons/svg/rss25.svg" %}" alt="rss icon"></a></p>
    </div>
  </div>
</section>
{% endblock %}