acquisitions/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web import views as web_views
from nda import views as nda_views
from team import urls as team_urls
from projects import urls as projects_urls
from projects import views as project_views
from news import urls as news_urls
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_docs.views import DRFDocsView


api_patterns = projects_urls.api_patterns + team_urls.api_patterns


urlpatterns = [
    url(r'^$', web_views.index),
    url(r'^guides$', web_views.guides),
    url(r'^api/$', DRFDocsView.as_view(), name='api_docs'),
    url(r'^api/', include(api_patterns, namespace='api')),
    url(r'^financials$', project_views.financials, name='financials'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^team/', include(team_urls.urlpatterns, namespace='team')),
    url(
        r'^projects/',
        include(projects_urls.project_patterns, namespace='projects')
    ),
    url(
        r'^buys/',
        include(projects_urls.buy_patterns, namespace='buys')
    ),
    url(
        r'^iaas/',
        include(projects_urls.iaa_patterns, namespace='iaas')
    ),
    url(
        r'^clients/',
        include(projects_urls.client_patterns, namespace='clients')
    ),
    url(
        r'^news/',
        include(news_urls.urlpatterns, namespace='news')
    ),
    url(r'^profile/$', web_views.profile),
    url(r'^profile/refresh_token/$', web_views.refresh_token),
    url(r'^profile/sign_nda/$', nda_views.sign_nda),
    # url(r'^auth/', include('uaa_client.urls', namespace='uaa_client')),
    url(r'^auth/', include('uaa_client.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^', include('uaa_client.fake_uaa_provider.urls',
                          namespace='fake_uaa_provider'))
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import include, url
from news import views
from news.feeds import LatestPosts

urlpatterns = [
    url(r'^$', views.posts, name='posts'),
    url(r'^rss/$', LatestPosts(), name='rss'),
    url(r'^(?P<slug>[a-z\-]+)$', views.post, name='post'),
]

nda/models.py
from django.db import models

# Create your models here.

nda/forms.py
import floppyforms.__future__ as forms


class NDAForm(forms.Form):
    agree = forms.BooleanField()

    def clean_agree(self):
        agree = self.cleaned_data['agree']
        if agree == True:
            return agree
        else:
            raise forms.ValidationError("You must agree to the terms of the NDA")

nda/views.py
import os
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from nda.forms import NDAForm


# Create your views here.
@login_required
def sign_nda(request):
    try:
        group = Group.objects.get(name='NDA Signed')
    except Group.DoesNotExist:
        print('NDA Signed group not yet created')
        raise Http404
    try:
        request.user.groups.get(id=group.id)
        return render(request, 'nda/already-signed.html')
    except Group.DoesNotExist:
        pass
    nda_form = NDAForm(request.POST or None)
    if nda_form.is_valid():
        request.user.groups.add(group)
        return render(request, 'nda/success.html')
    return render(request, 'nda/nda.html', {
        'nda_form': nda_form
    })

nda/templates/nda/already-signed.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-grid">
  <div class="usa-grid-one-full">
    <h1>Already signed!</h1>
    <p>
      You've previously signed the NDA. No need to do it again!
    </p>
  </div>
</section>
{% endblock %}

nda/templates/nda/buy_nda.html
{% extends "web/base.html" %}
{% load floppyforms %}
{% load markdown_deux_tags %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    {% markdown %}
    {% include "nda/markdown/buy_nda.md" %}
    {% endmarkdown %}
    <form class="" method="post">
      {% csrf_token %}
      {% form nda_form using %}
      {% formfield form.agree %}
      <label for="id_agree">I agree</label>
      {% endform %}
      <p><input type="submit" value="Submit"></p>
    </form>
  </div>
</section>
{% endblock %}

nda/templates/nda/nda.html
{% extends "web/base.html" %}
{% load floppyforms %}
{% load markdown_deux_tags %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    {% markdown %}
    {% include "nda/markdown/nda.md" %}
    {% endmarkdown %}
    <form class="" method="post">
      {% csrf_token %}
      {% form nda_form using %}
      {% formfield form.agree %}
      <label for="id_agree">I agree</label>
      {% endform %}
      <p><input type="submit" value="Submit"></p>
    </form>
  </div>
</section>
{% endblock %}

nda/templates/nda/success.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-grid">
  <div class="usa-grid-one-full">
    <h1>Success!</h1>
    <p>
      Thank you for signing the NDA. You've now been granted access to items requiring an NDA.
    </p>
  </div>
</section>
{% endblock %}