acquisitions/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web import views as web_views
from nda import views as nda_views
from team import urls as team_urls
from projects import urls as projects_urls
from projects import views as project_views
from news import urls as news_urls
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_docs.views import DRFDocsView


api_patterns = projects_urls.api_patterns + team_urls.api_patterns


urlpatterns = [
    url(r'^$', web_views.index),
    url(r'^guides$', web_views.guides),
    url(r'^api/$', DRFDocsView.as_view(), name='api_docs'),
    url(r'^api/', include(api_patterns, namespace='api')),
    url(r'^financials$', project_views.financials, name='financials'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^team/', include(team_urls.urlpatterns, namespace='team')),
    url(
        r'^projects/',
        include(projects_urls.project_patterns, namespace='projects')
    ),
    url(
        r'^buys/',
        include(projects_urls.buy_patterns, namespace='buys')
    ),
    url(
        r'^iaas/',
        include(projects_urls.iaa_patterns, namespace='iaas')
    ),
    url(
        r'^clients/',
        include(projects_urls.client_patterns, namespace='clients')
    ),
    url(
        r'^news/',
        include(news_urls.urlpatterns, namespace='news')
    ),
    url(r'^profile/$', web_views.profile),
    url(r'^profile/refresh_token/$', web_views.refresh_token),
    url(r'^profile/sign_nda/$', nda_views.sign_nda),
    # url(r'^auth/', include('uaa_client.urls', namespace='uaa_client')),
    url(r'^auth/', include('uaa_client.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^', include('uaa_client.fake_uaa_provider.urls',
                          namespace='fake_uaa_provider'))
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import include, url
from news import views
from news.feeds import LatestPosts

urlpatterns = [
    url(r'^$', views.posts, name='posts'),
    url(r'^rss/$', LatestPosts(), name='rss'),
    url(r'^(?P<slug>[a-z\-]+)$', views.post, name='post'),
]

projects/urls.py
from django.conf.urls import include, url
from projects import views
from rest_framework.urlpatterns import format_suffix_patterns


api_patterns = [
    url(r'^projects/$', views.ProjectList.as_view(), name='project-list'),
    url(r'^projects/(?P<pk>[0-9]+)$',
        views.ProjectDetail.as_view(),
        name='project-detail'),
    url(r'^buys/$', views.BuyList.as_view(), name='buy-list'),
    url(r'^buys/abpa/$', views.BuyList.as_view(), name='abpa-list'),
    url(r'^buys/abpa/(?P<pk>[0-9]+)$',
        views.BuyDetail.as_view(),
        name='abpa-detail'),
    url(r'^iaas/$', views.IAAList.as_view(), name='iaa-list'),
    url(r'^iaas/(?P<pk>[0-9]+)$',
        views.IAADetail.as_view(),
        name='iaa-detail'),
    url(r'^clients/$', views.ClientList.as_view(), name='client-list'),
    url(r'^clients/(?P<pk>[0-9]+)$',
        views.ClientDetail.as_view(),
        name='client-detail'),
]

iaa_patterns = [
    url(r'^$', views.iaas, name='iaas'),
    url(r'^create/$', views.edit_iaa, name='edit_iaa'),
    url(r'(?P<iaa>\w+)/$', views.iaa, name='iaa'),
    url(r'(?P<iaa>\w+)/edit/$', views.edit_iaa, name='edit_iaa'),
]

project_patterns = [
    url(r'^$', views.projects, name='projects'),
    url(r'^create/$', views.create_project, name='create_project'),
    url(r'(?P<project>\d+)/$', views.project, name='project'),
    url(r'(?P<project>\d+)/edit/$', views.edit_project, name='edit_project'),
]

buy_patterns = [
    url(r'^$', views.buys, name='buys'),
    url(r'^create/$', views.create_buy, name='create_buy'),
    url(r'(?P<buy>\d+)/$', views.buy, name='buy'),
    url(r'(?P<buy>\d+)/edit/$', views.edit_buy, name='edit_buy'),
    url(r'(?P<buy>\d+)/nda/$', views.buy_nda, name='buy_nda'),
    url(r'(?P<buy>\d+)/(?P<doc_type>\w+)/$', views.document, name='document'),
    url(
        r'(?P<buy>\d+)/(?P<doc_type>\w+)/download/(?P<doc_format>\w+)?$',
        views.download,
        name='download'
    ),
]

client_patterns = [
    url(r'^$', views.clients, name='clients'),
    url(r'^create/$', views.edit_client, name='edit_client'),
    url(r'^(?P<client>\w+)/$', views.client, name='client'),
    url(r'(?P<client>\d+)/edit/$', views.edit_client, name='edit_client'),
]

api_patterns = format_suffix_patterns(api_patterns)

projects/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.postgres.forms import SimpleArrayField
from projects.models import Buy, Project, IAA, AgencyOffice
from projects.widgets import DurationMultiWidget
from form_utils.forms import BetterModelForm
from form_utils.widgets import AutoResizeTextarea


class ClientForm(forms.ModelForm):
    class Meta:
        model = AgencyOffice
        fields = '__all__'


class IAAForm(forms.ModelForm):
    class Meta:
        model = IAA
        fields = '__all__'


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'


class CreateBuyForm(forms.ModelForm):
    class Meta:
        model = Buy
        fields = [
            'name',
            'description',
            'project',
            'budget',
            'procurement_method'
        ]


class EditBuyForm(forms.ModelForm):
    requirements = SimpleArrayField(
        forms.CharField(),
        delimiter='\n',
        help_text='Multiple requirements are allowed. Enter each one on its '
                  'own line. Additional formatting, like bullet points, will '
                  'be added later, so leave that out.',
        required=False,
        widget=forms.Textarea,
    )
    skills_needed = SimpleArrayField(
        forms.CharField(),
        delimiter='\n',
        help_text='Multiple skills are allowed. Enter each one on its '
                  'own line. Additional formatting, like bullet points, will '
                  'be added later, so leave that out.',
        required=False,
        widget=forms.Textarea,
    )

    def __init__(self, *args, **kwargs):
        super(EditBuyForm, self).__init__(*args, **kwargs)

        buy = kwargs['instance']
        team_members = User.objects.filter(project=buy.project.id)
        self.fields['technical_evaluation_panel'].queryset = team_members
        self.fields['product_owner'].queryset = team_members
        self.fields['product_lead'].queryset = team_members
        self.fields['acquisition_lead'].queryset = team_members
        self.fields['technical_lead'].queryset = team_members

    class Meta:
        model = Buy
        fields = '__all__'
        widgets = {
            # 'description': AutoResizeTextarea(),
            'base_period_length': DurationMultiWidget(),
            'option_period_length': DurationMultiWidget(),
            # 'technical_evaluation_panel': forms.CheckboxSelectMultiple()
        }

projects/views.py
import markdown
import pypandoc
import re
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.core.files.temp import NamedTemporaryFile
from rest_framework import viewsets, status, mixins, generics
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from projects.models import IAA, Project, Buy, AgencyOffice
from projects.serializers import (
    IAASerializer,
    ProjectSerializer,
    BuySerializer,
    ClientSerializer,
)
from projects.filters import (
    BuyFilter,
    ProjectFilter,
)
from projects.forms import (
    ClientForm,
    IAAForm,
    ProjectForm,
    CreateBuyForm,
    EditBuyForm,
)
from acquisitions import settings
from nda.forms import NDAForm


# Create your views here.

# Utilities
def _public_check(thing, user):
    if not thing.public:
        return user.has_perm('projects.view_project')
    else:
        return True


def _make_response(doc_content, name, doc_type, doc_format):
    response = HttpResponse(doc_content, content_type='text/plain')
    disposition = 'attachment; filename="{0} {1}.{2}"'.format(
        name,
        doc_type,
        doc_format,
    )
    response['Content-Disposition'] = disposition
    return response


def _get_doc(buy, doc_type, access_private=False):
    available_docs = [d for d in buy.available_docs(
        access_private=access_private
    )]
    # Check that the request is for a document that is available
    if doc_type not in available_docs:
        raise Http404
    doc_content = getattr(buy, doc_type)
    return doc_content


# Views
def iaas(request):
    return render(request, "projects/iaas.html")


def iaa(request, iaa):
    # Since we only want to show a page if the project exists, this can't
    # quite be an API-only thing. But most of the page is built via API.
    iaa = get_object_or_404(IAA, id=iaa)
    if not iaa.is_signed():
        if not request.user.has_perm('projects.view_project'):
            return render(request, "projects/private-page.html")
    return render(request, "projects/iaa.html", {"iaa": iaa})


def projects(request):
    return render(request, "projects/projects.html")


def project(request, project):
    # Since we only want to show a page if the project exists, this can't
    # quite be an API-only thing. But most of the page is built via API.
    project = get_object_or_404(Project, id=project)
    if not _public_check(project, request.user):
        return render(request, "projects/private-page.html")
    return render(request, "projects/project.html", {"project": project})


def buys(request):
    return render(request, "projects/buys.html")


def buy(request, buy):
    buy = get_object_or_404(Buy, id=buy)
    if not _public_check(buy, request.user):
        return render(request, "projects/private-page.html")
    if request.method == 'POST':
        doc_type = [i for i in request.POST if re.match("generate_\w+", i)]
        if len(doc_type) > 0:
            doc_type = doc_type[0][9:]
            buy.create_document(doc_type)
            return redirect('buys:document', buy.id, doc_type)
    access_private = request.user.is_staff
    documents = buy.available_docs(access_private=access_private)
    return render(
        request,
        "projects/buy.html",
        {
            "buy": buy,
            "documents": documents
        }
    )


def clients(request):
    return render(request, "projects/clients.html")


def client(request, client):
    client = get_object_or_404(AgencyOffice, id=client)
    if not client.is_public() and not request.user.has_perm('projects.view_project'):
        return render(request, "projects/private-page.html")
    else:
        return render(
            request,
            "projects/client.html",
            {
                "client": client,
            }
        )


@login_required
def edit_client(request, client=None):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            client = form.save()
            return redirect('clients:client', client.id)
    else:
        if client is not None:
            client = get_object_or_404(AgencyOffice, id=client)
        form = ClientForm(instance=client)
    return render(request, 'projects/edit_client.html', {
        'form': form
    })


@login_required
def create_iaa(request):
    if request.method == 'POST':
        form = IAAForm(request.POST)
        if form.is_valid():
            iaa = form.save()
            return redirect('iaas:iaa', iaa.id)
    else:
        form = IAAForm()
    return render(request, 'projects/edit_iaa.html', {
        'form': form,
    })


@login_required
def edit_iaa(request, iaa=None):
    iaa = get_object_or_404(IAA, id=iaa)
    if request.method == 'POST':
        form = IAAForm(request.POST, instance=iaa)
        if form.is_valid():
            iaa = form.save()
            return redirect('iaas:iaa', iaa.id)
    else:
        form = IAAForm(instance=iaa)
    return render(request, 'projects/edit_iaa.html', {
        'form': form,
        'iaa': iaa,
    })


@login_required
def create_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save()
            return redirect('projects:project', project.id)
    else:
        form = ProjectForm()
    return render(request, 'projects/edit_project.html', {
        'form': form,
    })


@login_required
def edit_project(request, project=project):
    project = get_object_or_404(Project, id=project)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            project = form.save()
            return redirect('projects:project', project.id)
    else:
        form = ProjectForm(instance=project)
    return render(request, 'projects/edit_project.html', {
        'form': form,
        'project': project,
    })


@login_required
def create_buy(request):
    if request.method == 'POST':
        form = CreateBuyForm(request.POST)
        if form.is_valid():
            buy = form.save()
            return redirect('buys:buy', buy.id)
    else:
        form = CreateBuyForm()
    return render(request, 'projects/create_buy.html', {
        'form': form
    })


@login_required
def edit_buy(request, buy):
    buy = get_object_or_404(Buy, id=buy)
    if request.method == 'POST':
        form = EditBuyForm(request.POST, instance=buy)
        if form.is_valid():
            form.save()
            return redirect('buys:buy', buy.id)
    else:
        form = EditBuyForm(instance=buy)
    return render(request, 'projects/edit_buy.html', {
        'buy': buy,
        'form': form
    })


@login_required
def buy_nda(request, buy):
    if buy is None:
        return redirect(reverse('buys:buys'))
    buy = Buy.objects.get(id=buy)
    nda_form = NDAForm(request.POST or None)
    if nda_form.is_valid():
        buy.nda_signed.add(request.user)
        return redirect(reverse('buys:buy', args=[buy.id]))
    return render(
        request,
        "nda/buy_nda.html",
        {"buy": buy, "nda_form": nda_form}
    )


def document(request, buy, doc_type):
    print('documents!')
    buy = get_object_or_404(Buy, id=buy)
    if not _public_check(buy, request.user):
        print('NO')
        raise Http404
    # Get the content of the document
    doc_content = _get_doc(buy, doc_type, request.user.is_staff)
    if doc_content is not None:
        print('yes!')
        return render(
            request,
            "projects/document.html",
            {
                "buy": buy,
                "document": doc_content
            }
        )
    else:
        # TODO: Give option to generate a document if it does not exist
        raise Http404


def download(request, buy, doc_type, doc_format):
    buy = get_object_or_404(Buy, id=buy)
    supported_formats = ['markdown', 'md', 'docx', 'pdf']
    # Get the content of the document
    doc_content = _get_doc(buy, doc_type)
    # Return markdown is the format isn't clear
    if doc_format not in supported_formats:
        doc_format = 'md'
    # Standardize format spelling
    if doc_format == 'markdown':
        doc_format = 'md'
    # Check that the user has access to view this document
    if not _public_check(buy, request.user):
        raise Http404
    if doc_content is not None:
        if doc_format == 'md':
            # Markdown is the simplest: since the content is already stored
            # that way, it can be sent back directly
            return _make_response(doc_content, buy.name, doc_type, doc_format)
        elif doc_format == 'docx':
            # For .docx, create a temporary file, use it as the output for
            # pandoc, and then send that file. Using NamedTemporaryFile means
            # that the file will be deleted as soon operations complete.
            dl = NamedTemporaryFile()
            output = pypandoc.convert_text(
                doc_content,
                'docx',
                format='markdown_github',
                outputfile=dl.name
            )
            return _make_response(doc_content, buy.name, doc_type, doc_format)
        elif doc_format == 'pdf':
            # This requires LaTeX support (via pdflatex) in addition to a
            # pandoc installation.
            dl = NamedTemporaryFile(suffix='.pdf')
            output = pypandoc.convert_text(
                doc_content,
                'pdf',
                format='markdown_github',
                outputfile=dl.name
            )
            return _make_response(doc_content, buy.name, doc_type, doc_format)
    else:
        raise Http404

projects/templates/projects/buy.html
{% extends "web/base.html" %}
{% load static from staticfiles %}
{% load document_tags %}

{% block resources %}
  <script src="{% static "js/a11y-dialog.min.js" %}"></script>
{% endblock %}

{% block content %}
{% if user in buy.technical_evaluation_panel.all and not user in buy.nda_signed.all %}
<div class="usa-alert usa-alert-warning">
  <div class="usa-alert-body">
    <h3 class="usa-alert-heading">You need to sign the NDA</h3>
    <p class="usa-alert-text">As a member of the technical evaluation panel, you'll need to sign the NDA before this buy can be issued. <a href="{% url 'buys:buy_nda' buy.id %}">Sign the NDA here</a>.</p>
  </div>
</div>
{% endif %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <h1>{{ buy.name }} {% if user.is_staff %}<a class="usa-button" href="{{ buy.get_absolute_url }}edit">Edit</a>{% endif %}</h1>
    {% if buy.is_private %}<div>This buy is not yet public.</div>{% endif %}
    <h2>Description</h2>
    <div id="description">
      {{ buy.description }}
    </div>
    <h2>Details</h2>
    <table class="usa-table-borderless">
      <tbody>
        <tr>
          <th scope="row">Status</th>
          <td>{{ buy.status }}</td>
        </tr>
        <tr>
          <th scope="row">Procurement Method</th>
          <td>{{ buy.procurement_method }}</td>
        </tr>
        <tr>
          <th scope="row">Set-Aside</th>
          <td>{{ buy.set_aside_status }}</td>
        </tr>
        <tr>
          <th scope="row">Posted on</th>
          <td>{{ buy.issue_date }}</td>
        </tr>
        <tr>
          <th scope="row">Questions due by</th>
          <td>{{ buy.questions_due_by }}</td>
        </tr>
        <tr>
          <th scope="row">Submissions due by</th>
          <td>{{ buy.submissions_due_by }}</td>
        </tr>
      </tbody>
    </table>
    {% for doc in documents %}
    {% if forloop.first %}<h2>Documents</h2>{% endif %}
      {% if forloop.counter0|divisibleby:"2" %}<div class="usa-grid-full acq-documents">{% endif %}
        <div class="usa-width-one-half" id="{{ doc }}">
          <h3>{{ doc|title_format }}</h3>
          {% if buy|has_document:doc %}
          <p><a href="{% url 'buys:document' buy.id doc %}">View</a></p>
          <p>Download: <a href="{% url 'buys:download' buy.id doc 'markdown' %}">.md</a> | <a href="{% url 'buys:download' buy.id doc 'docx' %}">.docx</a> | <a href="{% url 'buys:download' buy.id doc 'pdf' %}">.pdf</a></p>
          {% if perms.project.view_project %}
          <button onclick="connectButtons(this)" type="submit" name="generate_{{ doc }}" data-a11y-dialog-show="confirm-dialog">Regenerate</button>
          {% endif %}
          {% else %}
          {% if perms.project.view_project %}
          <form method="post">
            {% csrf_token %}
            <button type="submit" name="generate_{{ doc }}">Generate</button>
          </form>
          {% endif %}
          {% endif %}
        </div>
      {% if not forloop.counter0|divisibleby:"2" %}</div>{% endif %}
    {% if forloop.last %}</div>{% endif %}
    {% endfor %}
</section>
{% endblock %}

{% block modals %}
<div id="confirm-dialog" class="dialog" aria-hidden="true">
  <div class="dialog-overlay" tabindex="-1" data-a11y-dialog-hide>
    <div class="dialog-content" aria-labelledby="dialogTitle" aria-describedby="dialogDescription" role="dialog">
      <div role="document">
        <h1 id="dialogTitle" tabindex="0">Regenerate document</h1>

        <p id="dialogDescription">Regenerating will overwrite the existing document, including any changes made. Are you sure?</p>

        <form action="" method="post" target="_blank">
          {% csrf_token %}
          <button type="submit" name="button" id="confirm-button">I'm sure</button>
        </form>
        <button data-a11y-dialog-hide class="dialog-close" title="Close registration form">&times;</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  var dialogEl = document.getElementById('confirm-dialog');
  var dialog = new A11yDialog(dialogEl);
  function connectButtons(el) {
    // Sets the form submission name based on the specific "regenerate" button clicked
    const confirm = document.getElementById('confirm-button');
    confirm.name = el.name
  }
</script>
{% endblock %}

projects/templates/projects/buys.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <h1>Buys</h1>
    {% if perms.projects.view_project %}<div>Showing: <strong>public</strong> and <strong>non-public</strong> buys</div>{% endif %}
    {% if request.user.is_staff %}<div><a class="usa-button" href="/buys/create">Create Buy</a></div>{% endif %}
    <h2>Planning</h2>
    <div id="planning">

    </div>
    <h2>Out for Bid</h2>
    <div id="posted">

    </div>
    <h2>Awarded</h2>
    <div id="awarded">

    </div>
    <h2>Delivered</h2>
    <div id="delivered">

    </div>
  </div>
</section>
<script type="text/javascript">
  function createBuy(buy) {
    // Create a div element with information about the buy
    let div = document.createElement('div');
    div.id = 'buy-'+buy.id;
    let buyName = document.createElement('h3');
    let buyLink = document.createElement('a');
    buyLink.href = '/buys/'+buy.id;
    let nameContent = document.createTextNode(buy.name);
    buyLink.appendChild(nameContent);
    buyName.appendChild(buyLink);
    buyName.className = 'buyName';
    let buyType = document.createElement('p');
    let typeContent = document.createTextNode('Type: '+buy.procurement_method)
    buyType.appendChild(typeContent);
    let buyDescription = document.createElement('p');
    let descriptionContent = document.createTextNode(buy.description);
    buyDescription.appendChild(descriptionContent);
    buyDescription.className = 'buyDescription';
    div.appendChild(buyName);
    div.appendChild(buyType);
    div.appendChild(buyDescription);
    return div
  }
  const statuses = {
    "Planning": document.getElementById('planning'),
    "Out for Bid": document.getElementById('posted'),
    "Awarded": document.getElementById('awarded'),
    "Delivered": document.getElementById('delivered')
  }
  const r1 = new XMLHttpRequest();
  r1.open("GET", "/api/buys/", true);
  r1.onreadystatechange = function () {
    if (r1.readyState != 4 || r1.status != 200) return;
    var jsonResponse = JSON.parse(r1.responseText);
    if (jsonResponse.length > 0) {
      for (let buy of jsonResponse) {
        const state = statuses[buy.status];
        state.appendChild(createBuy(buy));
      }
    } else {
      let div = document.createElement("div");
      let content = document.createTextNode("No public buys");
      div.appendChild(content);
      current.appendChild(div);
    }
  };
  r1.send();
</script>
{% endblock %}

projects/templates/projects/clients.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <h1>Clients</h1>
    {% if perms.projects.view_project %}<p>Showing: <strong>Signed</strong> and <strong>unsigned</strong> IAAs</p>{% endif %}
    <p class="">
      A client has signed one or more IAAs with our office, authorizing work to be done.
    </p>
    <h2>Current</h2>
    <div id="current">

    </div>
  </div>
</section>
<script type="text/javascript">
  function createClient(client) {
    // Create a div element with information about the client
    let div = document.createElement('div');
    div.id = 'client-'+client.id;
    let clientName = document.createElement('h3');
    let clientLink = document.createElement('a');
    clientLink.href = '/clients/'+client.id;
    let nameContent = document.createTextNode(client.client);
    clientLink.appendChild(nameContent);
    clientName.appendChild(clientLink);
    clientName.className = 'clientName';
    div.appendChild(clientName);
    return div
  }
  function createIAA(iaa) {
    // Check for client iaa wrapper div
    let wrapper = document.getElementById('client-'+iaa.client.id+'-iaa-wrapper');
    let client = document.getElementById('client-'+iaa.client.id)
    if (!wrapper) {
      wrapper = document.createElement('div');
      wrapper.id = 'client-'+iaa.client.id+'-iaa-wrapper';
      wrapper.className = 'usa-grid';
      let sidebarWrapper = document.createElement('div');
      sidebarWrapper.className = 'usa-width-one-sixth';
      let sidebar = document.createElement('div');
      let sidebarTitle = document.createElement('h4');
      let sidebarContent = document.createTextNode('IAAs');
      sidebarTitle.appendChild(sidebarContent);
      sidebar.appendChild(sidebarTitle);
      sidebarWrapper.appendChild(sidebar);
      let main = document.createElement('div');
      main.className = 'usa-width-five-sixths';
      wrapper.appendChild(sidebarWrapper);
      wrapper.appendChild(main);
      client.appendChild(wrapper);
    }
    // Create iaa div
    let iaaDiv = document.createElement('div');
    let iaaName = document.createElement('h5');
    let nameContent = document.createTextNode(iaa.id);
    let iaaLink = document.createElement('a');
    iaaLink.href = '/iaas/'+iaa.id;
    iaaLink.appendChild(nameContent);
    iaaName.appendChild(iaaLink);
    let iaaDescription = document.createElement('div');
    // let descriptionContent = document.createTextNode(iaa.description);
    // iaaDescription.appendChild(descriptionContent);
    iaaDiv.appendChild(iaaName);
    // iaaDiv.appendChild(iaaDescription);
    wrapper.childNodes[1].appendChild(iaaDiv);
  }
  document.addEventListener("DOMContentLoaded", function(event) {
    let current = document.getElementById('current');
    let r1 = new XMLHttpRequest();
    r1.open("GET", "/api/clients/", true);
    r1.onreadystatechange = function () {
      if (r1.readyState != 4 || r1.status != 200) return;
      var jsonResponse = JSON.parse(r1.responseText);
      if (jsonResponse.length > 0) {
        for (let client of jsonResponse) {
          current.appendChild(createClient(client));
        }
      } else {
        let div = document.createElement("div");
        let content = document.createTextNode("No public clients");
        div.appendChild(content);
        current.appendChild(div);
      }
      let r2 = new XMLHttpRequest();
      r2.open("GET", "/api/iaas/", true);
      r2.onreadystatechange = function () {
        if (r2.readyState != 4 || r2.status != 200) return;
        var jsonResponse = JSON.parse(r2.responseText);
        for (let iaa of jsonResponse) {
          createIAA(iaa);
        }
      }
      r2.send();
    };
    r1.send();
  });
</script>
{% endblock %}

projects/templates/projects/create_buy.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <form class="" action="/buys/create" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Submit" />
    </form>
  </div>
</section>
{% endblock %}

projects/templates/projects/document.html
{% extends "web/base.html" %}
{% load markdown_deux_tags %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <p><a href="{{ buy.get_absolute_url }}">Back</a></p>
    {% markdown %}
    {{ document | safe }}
    {% endmarkdown %}
  </div>
</section>
{% endblock %}

projects/templates/projects/edit_client.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <form class="" action="/clients/create" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="">
        {{ form.name.errors }}
        {{ form.name.label_tag }}
        {{ form.name }}
      </div>
      <div class="">
        {{ form.agency.errors }}
        {{ form.agency.label_tag }}
        {{ form.agency }}
      </div>
      <div class="">
        {{ form.address.errors }}
        {{ form.address.label_tag }}
        {{ form.address }}
      </div>
      <input type="submit" value="Submit" />
    </form>
  </div>
</section>
{% endblock %}