acquisitions/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web import views as web_views
from nda import views as nda_views
from team import urls as team_urls
from projects import urls as projects_urls
from projects import views as project_views
from news import urls as news_urls
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_docs.views import DRFDocsView


api_patterns = projects_urls.api_patterns + team_urls.api_patterns


urlpatterns = [
    url(r'^$', web_views.index),
    url(r'^guides$', web_views.guides),
    url(r'^api/$', DRFDocsView.as_view(), name='api_docs'),
    url(r'^api/', include(api_patterns, namespace='api')),
    url(r'^financials$', project_views.financials, name='financials'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^team/', include(team_urls.urlpatterns, namespace='team')),
    url(
        r'^projects/',
        include(projects_urls.project_patterns, namespace='projects')
    ),
    url(
        r'^buys/',
        include(projects_urls.buy_patterns, namespace='buys')
    ),
    url(
        r'^iaas/',
        include(projects_urls.iaa_patterns, namespace='iaas')
    ),
    url(
        r'^clients/',
        include(projects_urls.client_patterns, namespace='clients')
    ),
    url(
        r'^news/',
        include(news_urls.urlpatterns, namespace='news')
    ),
    url(r'^profile/$', web_views.profile),
    url(r'^profile/refresh_token/$', web_views.refresh_token),
    url(r'^profile/sign_nda/$', nda_views.sign_nda),
    # url(r'^auth/', include('uaa_client.urls', namespace='uaa_client')),
    url(r'^auth/', include('uaa_client.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^', include('uaa_client.fake_uaa_provider.urls',
                          namespace='fake_uaa_provider'))
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import include, url
from news import views
from news.feeds import LatestPosts

urlpatterns = [
    url(r'^$', views.posts, name='posts'),
    url(r'^rss/$', LatestPosts(), name='rss'),
    url(r'^(?P<slug>[a-z\-]+)$', views.post, name='post'),
]

web/templates/web/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}TTS Office of Acquisitions{% endblock %}</title>
    <meta name="description" content="Making Procurement Joyful.">

    <meta property="og:type" content="website">
    <meta property="og:title" content="TTS Office of Acquisitions" />
    <meta name="twitter:title" content="TTS Office of Acquisitions">
    <meta property="og:url" content="https://{{ request.get_host }}/">
    <meta name="twitter:card" content="summary_large_image">
    <meta property="og:image" content="https://{{ request.get_host }}/static/web/img/astronaut.jpg">
    <meta name="twitter:image" content="https://{{ request.get_host }}/static/web/img/astronaut.jpg">
    <meta property="og:description" content="Making Procurement Joyful.">
    <meta name="twitter:description" content="Making Procurement Joyful.">

    <link rel="stylesheet" href="{% static "css/uswds.min.css" %}">
    <link rel="stylesheet" href="{% static "web/css/style.css" %}">
    <script src="{% static "js/uswds.min.js" %}"></script>

    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/favicons/favicon.ico" %}" />

    {% block resources %}{% endblock %}
  </head>
  <body>
    <a class="usa-skipnav" href="#main">Skip to main content</a>
    {% include "web/includes/header.html" %}
    <div class="usa-overlay"></div>
    <main id="main" aria-label="Content">

      {% block content %}

      {% endblock %}

    </main>
    {% block modals %}{% endblock modals %}
    {% include "web/includes/footer.html" %}
  </body>
</html>

web/templates/web/guides.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <h1>Guides</h1>
    <ul>
      <li><a href="https://modularcontracting.18f.gov/about/">Modular Contracting</a></li>
      <li><a href="https://pages.18f.gov/state-faq/">State Frequently Asked Questions</a></li>
      <li><a href="https://pages.18f.gov/digital-acquisition-playbook/">Digital Acquisitions Playbook</a></li>
      <li><a href="https://pages.18f.gov/contracting-cookbook/">Digital Contracting Cookbook</a></li>
      <li><a href="https://pages.18f.gov/partnership-playbook/">Partnership Playbook</a></li>
    </ul>
  </div>
</section>
{% endblock %}

web/templates/web/index.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-hero astronaut">
  <div class="usa-grid">
    <div class="usa-hero-callout usa-section-dark">
      <h2><span class="usa-hero-callout-alt">Agile Delivery Services BPA:</span> Making Procurements Joyful</h2>
      {# <a class="usa-hero-link" href="https://pages.18f.gov/ads-bpa">Current BPA orders</a>#}
      <a class="usa-button usa-button-big usa-button-secondary" href="https://pages.18f.gov/ads-bpa">See current task orders</a>
    </div>
  </div>
</section>
<section class="usa-grid">
  <div class="usa-width-one-full">
    <h1>The Latest</h1>
    {% for post in posts %}
    <h2>{{ post.title }}</h2>
    <p class="post-publication-info">
      <small>Posted on {{ post.publication_date }}<br>by {% for author in post.authors.all %}
        {{ author.get_full_name }}{% if not forloop.last %}, {% endif %}
      {% endfor %}</small>
    </p>
    <div class="post-content">
      {{ post.content }}
      <p><small><a href="{% url 'news:post' post.slug %}">Permalink</a></small></p>
    </div>
    {% empty %}
    <p>No updates yet, but stay tuned!</p>
    {% endfor %}
  </div>
</section>
{% endblock %}

web/templates/web/profile.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <h1>{{ user }}</h1>
    <div id="api-token">
      <h2>API Token</h2>
      {% if user.auth_token %}
      <div class="">
        Token: {{ user.auth_token }}
      </div>
      <a class="usa-button" href="/profile/refresh_token/">Refresh token</a>
      {% else %}
      <div class="">
        No API Token
      </div>
      <a class="usa-button" href="/profile/refresh_token/">Get a token</a>
      {% endif %}
    </div>
    <div id="nda-status">
      <h2>Non-Disclosure Agreement</h2>
      <div class="">
        {% if perms.projects.view_project %}
        You've signed the NDA.
        {% else %}
        <a class="usa-button" href="/profile/sign_nda/">Sign the NDA</a>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

web/templates/web/search.html
{% extends "web/base.html" %}

{% block content %}
<section class="usa-grid">
  <div class="usa-width-one-full">
    <h1>Search results ({{ results | length }})</h1>
    {% for result in results %}
      <a href="{{ result.get_absolute_url }}"><h2>{{ result }}</h2></a>
      <div class="">
        {{ result.rank }}
      </div>
    {% endfor %}
  </div>
</section>
{% endblock %}